CREATE TABLE IF NOT EXISTS employee (
  empId VARCHAR(10) NOT NULL,
  empName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS `tbl_doctors` (
  `DOCTOR_ID` varchar(20) NOT NULL,
  `DOCTOR_NAME` varchar(100) NOT NULL,
  `DEPARTMENT_NAME` varchar(50) NOT NULL,
  `MOBILE_NUMBER` varchar(13) NOT NULL,
  PRIMARY KEY (`DOCTOR_ID`)
);

CREATE TABLE IF NOT EXISTS `tbl_patients` (
  `PATIENT_ID` varchar(20) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `BIRTHDATE` timestamp(3) NOT NULL,
  `GENDER` varchar(12) NOT NULL,
  `MOBILE_NUMBER` varchar(13) NOT NULL,
  `NATIONALITY` varchar(30) NOT NULL,
  `ID_NUMBER` varchar(10) NOT NULL,
  PRIMARY KEY (`PATIENT_ID`)
);

CREATE TABLE IF NOT EXISTS `tbl_doctor_patients` (
  `DOCTOR_ID` varchar(20) NOT NULL,
  `PATIENT_ID` varchar(20) NOT NULL,
  KEY `PATIENT_ID_idx` (`PATIENT_ID`),
  KEY `DOCTOR_ID` (`DOCTOR_ID`),
  CONSTRAINT `DOCTOR_ID` FOREIGN KEY (`DOCTOR_ID`) REFERENCES `tbl_doctors` (`DOCTOR_ID`),
  CONSTRAINT `PATIENT_ID` FOREIGN KEY (`PATIENT_ID`) REFERENCES `tbl_patients` (`PATIENT_ID`)
);